# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['launcher_v5.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['gdown', 'requests', 'urllib3', 'bs4', 'filelock', 'tqdm'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='LatamRust_Cobbleverso',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
